version: '2'
services:
  interface:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - neuralnetwork
    tty: true
  neuralnetwork:
    image: neural_network
    tty: true